// src/ai/flows/assistant-chat-flow.ts
'use server';
/**
 * @fileOverview AI flow for a conversational assistant.
 * - getAssistantResponse - Function to trigger the flow.
 * - AssistantChatInput - Input type.
 * - AssistantChatOutput - Output type.
 */
import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const AssistantChatInputSchema = z.object({
  userInput: z.string().describe('The message sent by the user to the assistant.'),
  // Podríamos añadir historial de chat aquí en el futuro para contexto.
});
export type AssistantChatInput = z.infer<typeof AssistantChatInputSchema>;

const AssistantChatOutputSchema = z.object({
  assistantResponse: z.string().describe('The response generated by the AI assistant.'),
});
export type AssistantChatOutput = z.infer<typeof AssistantChatOutputSchema>;

export async function getAssistantResponse(input: AssistantChatInput): Promise<AssistantChatOutput> {
  return assistantChatFlow(input);
}

const assistantChatFlow = ai.defineFlow(
  {
    name: 'assistantChatFlow',
    inputSchema: AssistantChatInputSchema,
    outputSchema: AssistantChatOutputSchema,
  },
  async (input) => {
    const prompt = `
      Eres "Asistente Konecte", un amigable y útil asistente virtual para la plataforma inmobiliaria "konecte".

      "konecte" permite a los usuarios:
      - Ver y publicar listados de propiedades para venta o arriendo.
      - Publicar y buscar solicitudes específicas de propiedades.
      - Participar en foros de discusión para cada listado o solicitud (estilo Reddit).
      - Gestionar perfiles de usuario para seguir su actividad.
      - Utilizar herramientas de IA para encontrar coincidencias entre propiedades y solicitudes.
      - Visualizar datos de una Google Sheet configurada por un administrador.

      Tu objetivo es ayudar a los usuarios respondiendo sus preguntas sobre cómo usar "konecte", el mercado inmobiliario en Chile, o cualquier otra consulta general que puedan tener.
      Sé conciso, amable y profesional. No inventes información si no la conoces. Si te preguntan por una acción específica en la plataforma, guía al usuario sobre cómo podría realizarla (ej: 'Para publicar una propiedad, ve a la sección Publicar y sigue los pasos').

      Usuario: ${input.userInput}
      Asistente Konecte:`;

    const llmResponse = await ai.generate({
      prompt: prompt,
      config: {
        temperature: 0.7,
      },
    });

    return { assistantResponse: llmResponse.text || "Lo siento, no pude procesar tu solicitud en este momento." };
  }
);

