import { mysqlTable, int, varchar, timestamp, boolean, text, mysqlEnum, decimal, json } from 'drizzle-orm/mysql-core';

export const users = mysqlTable('users', {
  id: varchar('id', { length: 36 }).primaryKey(),
  name: varchar('name', { length: 255 }).notNull(),
  email: varchar('email', { length: 255 }).notNull(),
  passwordHash: varchar('password_hash', { length: 255 }).notNull(),
  rutTin: varchar('rut_tin', { length: 20 }).notNull(),
  phoneNumber: varchar('phone_number', { length: 50 }).notNull(),
  phoneVerified: boolean('phone_verified').default(false).notNull(),
  phoneOtp: varchar('phone_otp', { length: 10 }),
  phoneOtpExpiresAt: timestamp('phone_otp_expires_at'),
  avatarUrl: varchar('avatar_url', { length: 2048 }),
  roleId: varchar('role_id', { length: 36 }).notNull(),
  planId: varchar('plan_id', { length: 36 }),
  planExpiresAt: timestamp('plan_expires_at'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').onUpdateNow(),
  companyName: varchar('company_name', { length: 255 }),
  mainOperatingRegion: varchar('main_operating_region', { length: 100 }),
  mainOperatingCommune: varchar('main_operating_commune', { length: 100 }),
  propertiesInPortfolioCount: int('properties_in_portfolio_count'),
  websiteSocialMediaLink: varchar('website_social_media_link', { length: 2048 }),
});

export const properties = mysqlTable('properties', {
  id: varchar('id', { length: 255 }).primaryKey(),
  userId: varchar('user_id', { length: 36 }).notNull().references(() => users.id),
  source: mysqlEnum('source', ['web', 'bot']).default('web').notNull(),
  title: varchar('title', { length: 255 }).notNull(),
  slug: varchar('slug', { length: 255 }),
  description: text('description'),
  propertyType: mysqlEnum('property_type', ['rent', 'sale']).notNull(),
  category: mysqlEnum('category', ['apartment', 'house', 'condo', 'land', 'commercial', 'other']).notNull(),
  price: decimal('price', { precision: 14, scale: 2 }),
  currency: varchar('currency', { length: 10 }),
  address: varchar('address', { length: 255 }),
  city: varchar('city', { length: 100 }),
  country: varchar('country', { length: 100 }),
  region: varchar('region', { length: 100 }),
  bedrooms: int('bedrooms'),
  bathrooms: int('bathrooms'),
  totalAreaSqMeters: decimal('total_area_sq_meters', { precision: 10, scale: 2 }),
  usefulAreaSqMeters: decimal('useful_area_sq_meters', { precision: 10, scale: 2 }),
  parkingSpaces: int('parking_spaces'),
  petsAllowed: boolean('pets_allowed'),
  furnished: boolean('furnished'),
  commercialUseAllowed: boolean('commercial_use_allowed'),
  hasStorage: boolean('has_storage'),
  orientation: varchar('orientation', { length: 255 }),
  images: json('images'),
  features: json('features'),
  upvotes: int('upvotes').default(0),
  commentsCount: int('comments_count').default(0),
  isActive: boolean('is_active').default(true),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').onUpdateNow(),
  viewsCount: int('views_count').default(0),
  inquiriesCount: int('inquiries_count').default(0),
  publicationCode: varchar('publication_code', { length: 255 }),
});

export const searchRequests = mysqlTable('property_requests', {
  id: varchar('id', { length: 255 }).primaryKey(),
  userId: varchar('user_id', { length: 36 }).notNull().references(() => users.id),
  title: varchar('title', { length: 255 }).notNull(),
  slug: varchar('slug', { length: 255 }),
  description: text('description'),
  desiredPropertyTypeRent: boolean('desired_property_type_rent'),
  desiredPropertyTypeSale: boolean('desired_property_type_sale'),
  desiredCategoryApartment: boolean('desired_category_apartment'),
  desiredCategoryHouse: boolean('desired_category_house'),
  desiredCategoryCondo: boolean('desired_category_condo'),
  desiredCategoryLand: boolean('desired_category_land'),
  desiredCategoryCommercial: boolean('desired_category_commercial'),
  desiredCategoryOther: boolean('desired_category_other'),
  desiredLocationCity: varchar('desired_location_city', { length: 255 }),
  desiredLocationRegion: varchar('desired_location_region', { length: 255 }),
  desiredLocationNeighborhood: varchar('desired_location_neighborhood', { length: 255 }),
  minBedrooms: int('min_bedrooms'),
  minBathrooms: int('min_bathrooms'),
  budgetMax: decimal('budget_max', { precision: 14, scale: 2 }),
  commentsCount: int('comments_count').default(0),
  upvotes: int('upvotes').default(0),
  isActive: boolean('is_active').default(true),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').onUpdateNow(),
  openForBrokerCollaboration: boolean('open_for_broker_collaboration').default(false),
  publicationCode: varchar('publication_code', { length: 255 }),
});

export const plans = mysqlTable('plans', {
  id: varchar('id', { length: 36 }).primaryKey(),
  whatsappIntegration: boolean('whatsapp_integration'),
});

export const roles = mysqlTable('roles', {
    id: varchar('id', { length: 36 }).primaryKey(),
    name: varchar('name', { length: 255 }),
});

export const permissions = mysqlTable('permissions', {
    id: int('id').primaryKey(),
    name: varchar('name', { length: 255 }),
}); 